# Generated by Django 4.1.4 on 2023-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='aeropuerto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
